### ISSUE TITLE
umbraco cloud when Push changes development to live it's not working  

### ISSUE THREAD

**Issue by pankajinfo3** [skybrud/Skybrud.Umbraco.Redirects#72] opened 2020-09-18 06:37 UTC
umbraco cloud when Push changes development to live it's not working

**Comment by abjerner** [comment] 2020-09-20 18:53
Hi @pankajinfo3,

Transferring redirects between Cloud environments is not something that is currently supported.

**Closed as completed by abjerner** 2020-09-20 18:53 UTC

**Comment by robertemmerson** [comment] 2020-09-22 07:31
Hi @abjerner .  I don't think the issue is with cloud redirects. 
In Dev, the package allows me to configure redirects that have page section references (eg. .../pegasus?section=tutorials) without issue.
When I push the package to Live, any redirect entries with section references are dropped.  If I try to create one in Live, the entry returns an error that the redirect already exisits (referring to the parent entry without the section reference).
The package behaviour changes between Dev and Prod/Live.
Please advise.
