### ISSUE TITLE
Query String parameter causes 404 when ForwardQueryString enabled

### ISSUE THREAD

**Issue by mlhDevelopment** [skybrud/Skybrud.Umbraco.Redirects#128] opened 2022-02-17 13:41 UTC
## Issue Description
When a redirect is setup with ForwardQueryString enabled no redirect is being found when a query string parameter is present resulting in the 404 passing through Skybrud

## Versions
Umbraco 9.2
Skybrud 3.0.0-alpha007 (via NuGet) as well as github commits df8263a7402e2caa95c30cf3e43140fa2673ff6c and bd9f04f3383320a4c833ffce2aad0a8e601af50c

### Setup

- Create and verify content at /deep/dive
- Setup the redirect:

   - Sites: All Sites
   - Original Url: /deep/link
   - Destination: /deep/dive
   - Redirect Type: Temporary
   - Forward Query String: Enabled

### Test

1. Request endpoint /deep/link
2. Request endpoint /deep/link?foo
3. Request endpoint /deep/link?foo=bar

### Expected

1. Redirected to /deep/dive
2. Redirected to /deep/dive?foo
3. Redirected to /deep/dive?foo=bar

### Actual

1. Redirected to /deep/dive
2. HTTP 404
3. HTTP 404

## Notes

See also issues #104 and #43

**Comment by abjerner** [comment] 2022-02-17 14:03
@mlhDevelopment thanks again 👍 

#43 is for Umbraco 8. I think what you're proposing for Umbraco 9 already works in Umbraco 8. The problem described in the issue is that third parties may append a query string to the inbound URL (eg. `utm_medium=email`), and no redirect is then found if query string forwarding isn't enabled on the intended redirect.

I don't really have a good solution for this. One solution could be to make query string forwarding enabled by default for new redirects. I think we considered this a breaking change for the V8 package, but I wouldn't consider it so for V9 since we're still in alpha releases. But I'm not sure this is the correct way to go.

Another solution could be some kind of ignore list, so say the query string of the inbound request contains various `utm_` parameters that are in our ignore list, so remove them from the query string before looking for redirects. The downside is that these parameters would have to be known in advance, although they could be configurable somehow.

<hr />

#104 doesn't have a lot of information. I've considered closing it for lack of information, but left it open because I knew that I needed to have another look at the internal logic. Until now, I haven't really had the time to work on the V9, so I've worked a bit here and there, and it's likely the forward query string lookup was something I skipped and saved for later.

Since we're starting to need this package ourselves, I've been able to put a lot more time into the package (today and yesterday), so I'm also about to look into this part.

If you're up for adding a PR for this in the coming days, you're more than welcome to do so - then I'll look at some of the other task I have.

**Comment by mlhDevelopment** [comment] 2022-02-17 14:12
Yes, both #43 and #104 were not exact matches to what we were seeing. I just added PR #129 and after adding that on top of you work you just finished all redirects worked as expected. Caveat: I didn't test non-FowardQueryString redirects since I don't have them setup yet.

The main question is - why is the logic between `GetRedirectByPathAndQuery(guid, string, string)` and `GetRedirectByUrl(guid, string, string)` different? Should it be?

**Comment by abjerner** [comment] 2022-02-17 14:23
> The main question is - why is the logic between `GetRedirectByPathAndQuery(guid, string, string)` and `GetRedirectByUrl(guid, string, string)` different? Should it be?

Some of it may be leftovers from the V8 package. Before progressing to a beta release or a stable release, I need to go through the interface and the methods, and see if anything needs a cleanup. I think the `GetRedirectByUrl` would fit that category.

So I guess `GetRedirectByPathAndQuery` is a replacement for `GetRedirectByUrl`, but yes, they should ideally have done the same.

**Closed as completed** 2022-02-17 16:12 UTC
Labels: type/feature, umbraco/v9
