### ISSUE TITLE
7.6 support?

### ISSUE THREAD

**Issue by MichaelNielsenDK** [skybrud/Skybrud.Umbraco.Redirects#26] opened 2017-09-12 12:44 UTC
I'm having trouble getting this to work on Umbraco version 7.6.6.

We have used this package previously on multiple other solutions where it works fine, those however are v 7.5 and lower. 

I installed via NuGet, added httpModule, added Dashboard, added redirect /test to a node, but nothing happens. The log file does not reveal anything either. 

Are there any issues in using this on 7.6?

**Comment by abjerner** [comment] 2017-09-12 15:50
@MichaelNielsenDK I think it works fine. At least my 7.6.5 test solution works fine - I will try upgrading it to see whether that changes anything.

What happens when you go to the inbound URL of one of your redirects? And what is the status code? The redirects module only kicks in if the server responds with a 404 error. So on the off chance that your 404 page responds with a 200 status code, the redirects module does nothing.

**Comment by abjerner** [comment] 2017-09-12 16:00
Upgrading Umbraco is fast and easy these days :relaxed: The redirects module also seems to work in my now-running-7.6.6 test solution.

**Comment by MichaelNielsenDK** [comment] 2017-09-13 06:38
I am getting a 404
http://prntscr.com/gkitdw 

So it's quite strange... I'm 99.99% sure I haven't missed anything in the install or configuration, it's not like there is much to do anyway.

But I'll leave it for now, and have another one look at it, maybe another pair of eyes might spot something I cannot.

**Comment by abjerner** [comment] 2017-09-14 21:44
While working some more on the package the last few days, I've been testing the package using 7.6.6, and haven't experienced any issues with the HTTP module. Can you perhaps send me a copy of the `<modules>` section from your `Web.config`?

**Comment by bjarnef** [comment] 2017-09-14 22:11
@abjerner I have tested the Redirect package on a clean Umbraco 7.6.6 install and with the new default starterkit, and the redirect did seem to work as expected.

I thought it could be a conflict with Umbraco Deploy, since that is different from 7.5.x Cloud projects, which use Courier.

I tried cloning the project @MichaelNielsenDK was working on, but I didn't see the module in web.config - only the httpmodule `RedirectsHttpModule` under `<system.web>` and `<httpModules>`

```
<httpModules>
    <add name="ScriptModule" type="System.Web.Handlers.ScriptModule, System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" />

    <remove name="RedirectsHttpModule" />
    <add name="RedirectsHttpModule" type="Skybrud.Umbraco.Redirects.Routing.RedirectsHttpModule, Skybrud.Umbraco.Redirects" />

    <add name="UmbracoModule" type="Umbraco.Web.UmbracoModule,umbraco" />
    <add name="ClientDependencyModule" type="ClientDependency.Core.Module.ClientDependencyModule, ClientDependency.Core" />
    <add name="ImageProcessorModule" type="ImageProcessor.Web.HttpModules.ImageProcessingModule, ImageProcessor.Web" />
</httpModules>
```

So a redirect from `/test` to `/products` didn't redirect, but was just showing the regular 404-page.

After adding the `RedirectsHttpModule` under `<system.webServer>` and `<modules>` the redirect was working. I have only tested it on local environment, but it should also work on live environment.

```
<system.webServer>
    <modules runAllManagedModulesForAllRequests="true">
      <remove name="WebDAVModule" />
      <remove name="UmbracoModule" />
      <add name="UmbracoModule" type="Umbraco.Web.UmbracoModule,umbraco" />

      <remove name="RedirectsHttpModule" />
      <add name="RedirectsHttpModule" type="Skybrud.Umbraco.Redirects.Routing.RedirectsHttpModule, Skybrud.Umbraco.Redirects" />

      <remove name="ScriptModule" />
      <add name="ScriptModule" preCondition="managedHandler" type="System.Web.Handlers.ScriptModule, System.Web.Extensions, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" />
      <remove name="ClientDependencyModule" />
      <add name="ClientDependencyModule" type="ClientDependency.Core.Module.ClientDependencyModule, ClientDependency.Core" />
      <!-- Needed for login/membership to work on homepage (as per http://stackoverflow.com/questions/218057/httpcontext-current-session-is-null-when-routing-requests) -->
      <remove name="FormsAuthentication" />
      <add name="FormsAuthentication" type="System.Web.Security.FormsAuthenticationModule" />
      <add name="ImageProcessorModule" type="ImageProcessor.Web.HttpModules.ImageProcessingModule, ImageProcessor.Web" />
    </modules>
</system.webServer>
```

**Comment by abjerner** [comment] 2017-09-18 21:00
As @bjarnef has confirmed this was a configuration issue, I'm closing this issue.

**Closed by abjerner** 2017-09-18 21:00 UTC
Labels: bug
