### ISSUE TITLE
Bug: Can't create documents without content

### ISSUE THREAD

**Issue by sebastiandammark** [skybrud/Skybrud.Umbraco.Redirects#130] opened 2022-03-09 16:21 UTC
If you're trying to create a document/node where **Redirects** is the first tab, the document name field is disabled.
This leads to not being able to save the page, unless you switch to the **info** tab first.

<img width="692" alt="image" src="https://user-images.githubusercontent.com/1575483/157480143-ea0b922d-b60b-4f63-98a8-c9eea419b762.png">

**Comment by abjerner** [comment] 2022-03-09 16:26
Hi @sebastiandammark 

As mentioned on Slack, this is a duplicate of https://github.com/skybrud/Skybrud.Umbraco.Redirects/issues/123

The bug has been fixed, but I've yet to push a new release. Hopefully I'll be able to do that soon 😉

**Closed as completed by abjerner** 2022-03-09 16:26 UTC
Labels: type/bug, umbraco/v9

**Comment by abjerner** [comment] 2022-03-10 15:16
Was a bit too quick to reply, so this is a duplicate of #120 and not #123.

#120 is not really a bug, but something that can be configured through code (see my comment in the issue for more information).
