### ISSUE TITLE
Redirects has to be double saved

### ISSUE THREAD

**Issue by albinbrengesjo** [skybrud/Skybrud.Umbraco.Redirects#132] opened 2022-04-14 14:20 UTC
Hi there,

Bumped into a weird issue where the redirect doesnt work at first glance after adding it. I had to add it, manually click "edit" on the redirect I just created and then hit "save" in order to make it work properly. Running version 3.0.0 of skybrud on umbraco 9.3.1. Anyone else experience the same problem?

**Comment by callumbwhyte** [comment] 2022-04-20 17:28
@albinbrengesjo I can confirm we are seeing the same...

The difference seems to be the removal of a trailing slash from the "Original URL" after saving. e.g. `/some-page/` is the value initially saved on creation, while `/some-page` is the value saved after editing.

The [`EditRedirect`](https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/v3/main/src/Skybrud.Umbraco.Redirects/Controllers/Api/RedirectsController.cs#L118) in the API seems to trim the trailing slash (amongst other things), while the `AddRedirect` method does not. I'm not really sure why removing the trailing slash is needed, perhaps @abjerner can confirm?

I have attempted a fix in PR #134 😎

**Comment by abjerner** [comment] 2022-04-21 17:30
Hi @albinbrengesjo and thanks for reporting this 👍 

As Callum mentions, this sounds like that trailing slashes are not properly removed from the inbound URL when adding new redirects.

Via Callum's PR, this should now be fixed in the latest release:

https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v3.0.2

Could you test and confirm whether this fixes your issues?

**Comment by abjerner** [comment] 2022-04-27 09:07
@albinbrengesjo as I haven't heard back from you, I'm closing this issue on the assumption that it works with [v3.0.2](https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v3.0.2) and newer.

If you're still experiencing issues after upgrading, feel free to open the issue again 😉

**Closed as completed by abjerner** 2022-04-27 09:07 UTC
Labels: type/bug, umbraco/v9
